name: jit
channels:
  - pytorch
  - defaults
  - nvidia
dependencies:
  - python=3.10
  - pip=22.3
  - pytorch-cuda=12.4
  - pytorch=2.5.1
  - torchvision=0.20.1
  - numpy=1.22
  - pip:
    - opencv-python==4.11.0.86
    - timm==0.9.12
    - tensorboard==2.10.0
    - scipy==1.9.1
    - einops==0.8.1
    - gdown==5.2.0
    - -e git+https://github.com/LTH14/torch-fidelity.git@master#egg=torch-fidelity
